version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    reviewers:
      - "matusboa"
    assignees:
      - "matusboa"
    commit-message:
      prefix: "deps(github): "
  - package-ecosystem: "composer"
    directory: "./"
    schedule:
      interval: "weekly"
    reviewers:
      - "matusboa"
    assignees:
      - "matusboa"
    commit-message:
      prefix: "deps(composer): "